## Template config file. 
## Here you can specify the paths to the input and output, and other additional parameters.
## Arguments are specified in a key:value format, do NOT change the key names.


## Input data

# It is recommended to provide absolute paths, i.e. beginning with root (/). 
# For relative paths, the root directory is the location from which snakemake is called.

# Reference protein database. 
reference_p: /path/to/reference/proteome 
  
# Fastq files containing paired RNA-seq reads.
samples: 
  sample_1: #Sample 1. Provide the paired files as a list of 2 items.
    [ /path/to/sample1_L.fastq, /path/to/smaple1_R.fastq ] # Do not remove the [ and ]. Separate the file names by a comma.
  sample_2: #Sample 2.
    [ /path/to/sample2_L.fastq, /path/to/sample2_R.fastq]
  #add more samples as needed
  
# Output folder 
# It is recommended to provide absolute paths, i.e. beginning with root (/). 
# For relative paths, the root directory is the location from which snakemake is called.
out_dir: /path/to/output/folder
