out_dir:
  output/
reference_p:
  sample_data/reference.fa
samples:
  sample_1:
    [sample_data/sample_01_1.fasta, sample_data/sample_01_2.fasta]
  sample_2:
    [sample_data/sample_02_1.fasta, sample_data/sample_02_2.fasta]
  sample_3:
    [sample_data/sample_03_1.fasta, sample_data/sample_03_2.fasta]
  sample_4:
    [sample_data/sample_04_1.fasta, sample_data/sample_04_2.fasta]
