out_dir:
  output/
reference_p:
  sample_data/reference.fa
reads:
  sample_1:
    [sample_data/sample_01_1.fasta, sample_data/sample_01_2.fasta]
  sample_2:
    [sample_data/sample_02_1.fasta, sample_data/sample_02_2.fasta]

training: "no"
